apiVersion: v2
name: nginx
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.15.0
dependencies:
- name: nginx-ingress
  version: 1.26.2
  repository: https://kubernetes-charts.storage.googleapis.com/
