apiVersion: v2
name: nfs-client-provisioner
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.15.0
dependencies:
- name: nfs-client-provisioner
  version: 1.2.8
  repository: https://kubernetes-charts.storage.googleapis.com/
