apiVersion: v2
name: prometheus
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.15.0
dependencies:
- name: prometheus-operator
  version: 6.7.3
  repository: https://kubernetes-charts.storage.googleapis.com/
