apiVersion: v2
name: metallb
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.15.0
dependencies:
- name: metallb
  version: 0.11.2
  repository: https://kubernetes-charts.storage.googleapis.com/
