apiVersion: v2
name: mysql
description: A Helm chart for Kubernetes
type: application
version: 1.0.0
appVersion: 1.15.0
dependencies:
- name: base
  version: 0.1.0
  repository: file://../base
- name: mysql
  version: 1.5.0
  repository: https://kubernetes-charts.storage.googleapis.com/
  alias: mysql
